POST http://localhost:8080/events
content-type: application/json
# Authorization: TOKEN

{
  "title": "event5",
  "description": "event1 description",
  "dateTime": "2006-01-02T15:04:05Z",
  "location": "event1 location"
}