PUT http://localhost:8080/events/1
content-type: application/json

{
  "title": "eventEdited",
  "description": "Updated description",
  "dateTime": "2006-01-02T15:04:05Z",
  "location": "Updated location"
}